version: '3.8'

services:
  app:
    image: "registry.go2tr.ir/nima.mahini/nimagram:${CI_PIPELINE_ID}"
    container_name: "chat"
    ports:
      - "3333:3333"
      - "8080:8080"
    networks:
      - rope
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.chat.entrypoints=http,https"
      - "traefik.http.routers.chat.tls.certresolver=letsencrypt"
      - "traefik.http.routers.chat.rule=Host(`nima-chat.go2tr.work`)"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"





networks:
  rope:
    external: true
  web:
    external: true