services:
  app:
    image: "registry.go2tr.ir/nima.mahini/nimagram:${CI_PIPELINE_ID}"
    container_name: "chat"
    ports:
      - "3333:3333"
  pg:
    image: postgres:16-alpine
    container_name: "postgres_chat"
    ports:
      - "5432:5432"


