services:
  app:
    image: "registry.go2tr.ir/nima.mahini/nimagram:${CI_PIPELINE_ID}"
    container_name: "chat"
    depends_on:
      - pg
    ports:
      - "3333:3333"

  pg:
    image: postgres:16-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


volumes:
  postgres_data:
